version: '3'
services:

  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    expose:
      - 27017
    ports:
      - 27017:27017
    volumes:
      - mongodata:/data/db 
    networks:
      - my-network  
    
networks:
  my-network:
    driver: bridge

volumes:
  mongodata:
    driver: local
